kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: dev-binding
    namespace: app1
subjects:
  - kind: User
    name: user1
    apiGroup: ""
roleRef:
    kind: Role
    name: developer
    apiGroup: ""
